2018-11-20 05:57:32,020 (7906/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2018-11-20 05:58:30,462 (7906/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT COUNT(*) FROM dy', error: ProgrammingError('relation "dy" does not exist\n')
2018-11-20 05:58:30,463 (7906/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 357, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 389, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.ProgrammingError: relation "dy" does not exist\n\n'
2018-11-20 05:59:49,488 (7906/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT COUNT(*) FROM  dy', error: ProgrammingError('relation "dy" does not exist\n')
2018-11-20 05:59:49,488 (7906/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 357, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 389, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.ProgrammingError: relation "dy" does not exist\n\n'
2019-02-14 18:12:41,557 (46260/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-02-14 18:15:09,437 (46329/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-02-14 18:15:14,960 (46329/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 463, in connect\n    application_name=\'pgcli\', **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 197, in __init__\n    self.connect()\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 239, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 472, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 197, in __init__\n    self.connect()\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 239, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "\xa0-U" does not exist\n\n'
2019-02-14 18:15:53,740 (46379/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-02-14 18:17:12,911 (46379/MainThread) pgcli.pgexecute ERROR - sql: 'help', error: ProgrammingError('syntax error at or near "help"\nLINE 1: help\n        ^\n')
2019-02-14 18:17:12,912 (46379/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 357, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 389, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.ProgrammingError: syntax error at or near "help"\nLINE 1: help\n        ^\n\n'
2019-02-14 18:17:14,980 (46379/MainThread) pgcli.pgexecute ERROR - sql: '?', error: ProgrammingError('syntax error at or near "?"\nLINE 1: ?\n        ^\n')
2019-02-14 18:17:14,981 (46379/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 357, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 389, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.ProgrammingError: syntax error at or near "?"\nLINE 1: ?\n        ^\n\n'
2019-02-14 18:19:59,877 (46618/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-02-15 12:25:57,768 (4897/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-02-15 18:12:47,068 (8389/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-02-15 18:13:28,203 (8389/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 463, in connect\n    application_name=\'pgcli\', **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 197, in __init__\n    self.connect()\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 239, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 472, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 197, in __init__\n    self.connect()\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 239, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "clever"\nFATAL:  password authentication failed for user "clever"\n\n'
2019-02-15 18:17:10,168 (8422/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-02-15 18:17:12,194 (8422/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 474, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 463, in connect\n    application_name=\'pgcli\', **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 197, in __init__\n    self.connect()\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 239, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not send data to server: Socket is not connected\ncould not send SSL negotiation packet: Socket is not connected\n\n'
2019-02-15 18:18:51,520 (8675/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-02-15 18:18:53,585 (8675/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 474, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 463, in connect\n    application_name=\'pgcli\', **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 197, in __init__\n    self.connect()\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 239, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not send data to server: Socket is not connected\ncould not send SSL negotiation packet: Socket is not connected\n\n'
2019-02-15 18:19:32,201 (8680/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-03-08 14:56:57,637 (3798/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-03-08 14:56:57,646 (3798/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 474, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 463, in connect\n    application_name=\'pgcli\', **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 197, in __init__\n    self.connect()\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 239, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2019-03-13 16:31:35,931 (25841/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2019-03-13 16:31:35,940 (25841/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 474, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/main.py", line 463, in connect\n    application_name=\'pgcli\', **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 197, in __init__\n    self.connect()\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/pgcli/pgexecute.py", line 239, in connect\n    **kwargs)\n  File "/usr/local/Cellar/pgcli/2.0.0/libexec/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
